name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_dispatch:

env:
  REVISION: 0.1-SNAPSHOT

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            runner: ubuntu-22.04
            classifier: linux_amd64
            lib-name: libopenzl_jni.so
            run-tests: true
          - name: linux-aarch64
            runner: ubuntu-22.04-arm64
            classifier: linux_aarch64
            lib-name: libopenzl_jni.so
            run-tests: false
          - name: macos-x86_64
            runner: macos-13
            classifier: macos_x86_64
            lib-name: libopenzl_jni.dylib
            run-tests: false
          - name: macos-arm64
            runner: macos-14
            classifier: macos_aarch64
            lib-name: libopenzl_jni.dylib
            run-tests: false
          - name: windows-x86_64
            runner: windows-2022
            classifier: windows_amd64
            lib-name: openzl_jni.dll
            run-tests: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake ninja || true

      - name: Install build dependencies (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' --yes
          choco install ninja --yes

      - name: Set up MSVC toolchain
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B cmake_build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build native library
        shell: bash
        run: cmake --build cmake_build --target openzl_jni

      - name: Stage native artifact
        shell: bash
        run: |
          dest="JNI/openzl-jni/src/main/resources/lib/${{ matrix.classifier }}"
          mkdir -p "$dest"
          cp cmake_build/cli/${{ matrix.lib-name }} "$dest/"

      - name: Run JNI tests
        if: matrix.run-tests == true
        shell: bash
        run: |
          mvn -f JNI/pom.xml -pl openzl-jni -am \
            -Drevision=${REVISION} \
            -Dplatform.classifier=${{ matrix.classifier }} \
            -Dgpg.skip=true test

      - name: Package classifier JAR
        shell: bash
        run: |
          mvn -f JNI/pom.xml -pl openzl-jni -am \
            -Drevision=${REVISION} \
            -Dplatform.classifier=${{ matrix.classifier }} \
            -Dgpg.skip=true -DskipTests package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openzl-jni-${{ matrix.classifier }}
          retention-days: 7
          path: |
            JNI/openzl-jni/target/*${{ matrix.classifier }}*.jar
            JNI/openzl-jni/target/*.pom
