name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  jni-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run JNI unit tests
        run: mvn -f JNI/pom.xml -pl openzl-jni -am -Dgpg.skip=true test
