name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  jni-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install native build deps
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential ninja-build
      - name: Build native library
        run: |
          cmake -S . -B cmake_build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake_build --target openzl_jni
          cp cmake_build/cli/libopenzl_jni.so JNI/openzl-jni/src/main/resources/lib/linux_amd64/
      - name: Run JNI unit tests
        run: mvn -f JNI/pom.xml -pl openzl-jni -am -Dgpg.skip=true clean test
