name: Update sitemap lastmod

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update <lastmod> date in sitemap.xml
        run: |
          DATE=$(date -u +"%Y-%m-%d")
          echo "Updating sitemap.xml lastmod to $DATE"
          sed -i "s|<lastmod>.*</lastmod>|<lastmod>$DATE</lastmod>|g" docs/sitemap.xml

      - name: Commit and push if changed
        run: |
          if [[ -n $(git status --porcelain docs/sitemap.xml) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/sitemap.xml
            git commit -m "chore: update sitemap lastmod to $DATE [skip ci]"
            git push
          else
            echo "No sitemap changes — skipping commit."
          fi
